<?php return array(
    'root' => array(
        'name' => 'cakephp/app',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'brick/varexporter' => array(
            'pretty_version' => '0.3.7',
            'version' => '0.3.7.0',
            'reference' => '3e263cd718d242594c52963760fee2059fd5833c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/varexporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/app' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/bake' => array(
            'pretty_version' => '2.8.2',
            'version' => '2.8.2.0',
            'reference' => 'ef021497ab517c33ecd97d2184200d8990ffc0ab',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/bake',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/cakephp' => array(
            'pretty_version' => '4.4.8',
            'version' => '4.4.8.0',
            'reference' => 'ad188775dde89ad758dad9923ff558900914d59c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cakephp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/cakephp-codesniffer' => array(
            'pretty_version' => '4.6.0',
            'version' => '4.6.0.0',
            'reference' => '5a64e6e6434128f6a1549318de86c564737d5cda',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../cakephp/cakephp-codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/chronos' => array(
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'reference' => 'a21b7b633f483c4cf525d200219d200f551ee38b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/chronos',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/collection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/datasource' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/debug_kit' => array(
            'pretty_version' => '4.9.2',
            'version' => '4.9.2.0',
            'reference' => 'c6590fca606783bce5b0564a2997cd76042cf652',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/debug_kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/event' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/i18n' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/migrations' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => 'bbe44b610bbf51bda751114ecabfe5dd172a6dab',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/orm' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/plugin-installer' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'e27027aa2d3d8ab64452c6817629558685a064cb',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cakephp/plugin-installer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cakephp/twig-view' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '14df50360b809a171d0688020fbdfe513763f89b',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/twig-view',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'cakephp/utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'cakephp/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.4.8',
            ),
        ),
        'ceeram/cakepdf' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.1.2',
            ),
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.4',
            'version' => '1.3.4.0',
            'reference' => '69098eca243998b53eed7a48d82dedd28b447cd5',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/class-map-generator' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '1e1cb2b791facb2dfe32932a7718cf2571187513',
            'type' => 'library',
            'install_path' => __DIR__ . '/./class-map-generator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/composer' => array(
            'pretty_version' => '2.4.4',
            'version' => '2.4.4.0',
            'reference' => 'e8d9087229bcdbc5867594d3098091412f1130cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/metadata-minifier' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c549d23829536f0d0e984aaabbf02af91f443207',
            'type' => 'library',
            'install_path' => __DIR__ . '/./metadata-minifier',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '4bff79ddd77851fe3cdd11616ed3f92841ba5bd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.7',
            'version' => '1.5.7.0',
            'reference' => 'c848241796da2abf65837d51dce1fae55a960149',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'ced299686f41dce890debac69273b47ffe98a40c',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v0.7.2',
            'version' => '0.7.2.0',
            'reference' => '1c968e542d8843d7cd71de3c5c9c3ff3ad71a1db',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'c5310df0e22c758c85ea5288175fc6cd777bc085',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofcake/cakepdf' => array(
            'pretty_version' => '4.1.2',
            'version' => '4.1.2.0',
            'reference' => '1df6dd0ec0e74e1a7a6e61535a5e882f755eb94e',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../friendsofcake/cakepdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofcake/cakephp-csvview' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'a46b677860ff467e2e435de8bf17af8af1bffdc5',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../friendsofcake/cakephp-csvview',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.5.0',
            'version' => '7.5.0.0',
            'reference' => 'b50a2a1251152e43f6a37f0fa053e730a67d25ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.3',
            'version' => '2.4.3.0',
            'reference' => '67c26b443f348a51926030c83481b85718457d3d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jasny/twig-extensions' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'a694eb02f6fc14ff8e2fceb8b80882c0c926102b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasny/twig-extensions',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jdorn/sql-formatter' => array(
            'pretty_version' => 'v1.2.17',
            'version' => '1.2.17.0',
            'reference' => '64990d96e0959dff8e059dfcdc1af130728d92bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jdorn/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'josegonzalez/dotenv' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'f19174d9d7213a6c20e8e5e268aa7dd042d821ca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../josegonzalez/dotenv',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.12',
            'version' => '5.2.12.0',
            'reference' => 'ad87d5a5ca981228e0e205c2bc7dfb8e24559b60',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'klaviyo/api' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'a27d2c9ee10cc61db1de529096831e0c80c2cd16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../klaviyo/api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'klaviyo/php-sdk' => array(
            'pretty_version' => '2.3.6',
            'version' => '2.3.6.0',
            'reference' => '86ef89cb085286d6d41c453dd9b274c4fda2f2ca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../klaviyo/php-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'klaviyo/sdk' => array(
            'pretty_version' => '1.0.3.20220329',
            'version' => '1.0.3.20220329',
            'reference' => 'f277387007c7a84765e4b12802de6c18c7865fa5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../klaviyo/sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-diactoros' => array(
            'pretty_version' => '2.22.0',
            'version' => '2.22.0.0',
            'reference' => 'df8c7f9e11d854269f4aa7c06ffa38caa42e4405',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-diactoros',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-httphandlerrunner' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => 'd15af53895fd581b5a448a09fd9a4baebc4ae6e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-httphandlerrunner',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '375d13cb828649599ef5d48a339c4af7a26cd0ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'm1/env' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '5c296e3e13450a207e12b343f3af1d7ab569f6f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../m1/env',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.6',
            'version' => '2.7.6.0',
            'reference' => '897eb517a343a2281f11bc5556d6548db7d93947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.41',
            'version' => '2.8.41.0',
            'reference' => 'fc9cccd4d3706d5a7537b562b59cc18f9e4c0cb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.15.2',
            'version' => '4.15.2.0',
            'reference' => 'f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.4',
            'version' => '0.5.4.0',
            'reference' => 'dd448ad1ce34c63d09baccd05415e361300c35b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'reference' => '76876c6cf3080bcb6f249d7d59705108166a6685',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.15.0',
            'version' => '1.15.0.0',
            'reference' => '6ff970a7101acfe99b3048e4bbfbc094e55c5b04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.20',
            'version' => '9.2.20.0',
            'reference' => 'af7463c955007de36db0c5e26d03e2f933c2e980',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.27',
            'version' => '9.5.27.0',
            'reference' => 'a2bc7ffdca99f92d959b3f2270529334030bba38',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-server-handler' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'aff2f80e33b7f026ec96bb42f63242dc50ffcae7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-server-middleware' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2296f45510945530b9dceb8bcedb5cb84d40c5f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-server-middleware',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'ef29f6d262798707a9edd554e2b82517ef3a9376',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '8707bf3cea6f710bf6ef05491234e3ab06f6432a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'reference' => '234f8fd1023c9158e2314fa9d7d0e6a83db42910',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'robmorgan/phinx' => array(
            'pretty_version' => '0.13.3',
            'version' => '0.13.3.0',
            'reference' => 'da741d10879bcdd235a830d589ae51659f746262',
            'type' => 'library',
            'install_path' => __DIR__ . '/../robmorgan/phinx',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.4.0',
            'version' => '8.4.0.0',
            'reference' => 'e41d2140031d533348b2192a83f02d8dd8a71d30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => 'fa0f136dd2334583309d32b62544682ee972b51a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'reference' => '1b5dff7bb151a4db11d49d90e5408e4e938270f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'reference' => '0ca8db5a5fc9c8646244e629625ac486fa286bf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => '4211420d25eba80712bff236a98960ef68b866b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'ea2f4014f163c1be4c601b9b7bd6af81ba8d701c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/signal-handler' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'f69d119511dc0360440cdbdaa71829c149b7be75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/signal-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'slevomat/coding-standard' => array(
            'pretty_version' => '8.7.0',
            'version' => '8.7.0.0',
            'reference' => '326d195209d196be02f8c2a0034529262fc7ffcc',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../slevomat/coding-standard',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => '1359e176e9307e906dc3d890bcc9603ff6d90619',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => 'ebf27792246165a2a0b6b69ec9c620cac8c5a2f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v6.2.1',
            'version' => '6.2.1.0',
            'reference' => '58f6cef5dc5f641b7bbdbf8b32b44cc926c35f3f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'reference' => '1ee04c65529dea5d8744774d474e7cbd2f1206d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => '50b2523c874605cf3d4acf7a9e2b30b6a440a016',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => 'eb2355f69519e4ef33f1835bca4c935f5d42e570',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '511a08c03c1960e08a883f4cffcacd219b758354',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => 'ba6e55359f8f755fe996c58a81e00eaa67a35877',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'reference' => '925e713fe8fcacf6bc05e936edd8dd5441a21239',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'reference' => '145702685e0d12f81d755c71127bfff7582fdd36',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.6.1',
            'version' => '6.6.1.0',
            'reference' => 'a336b531f6f6b5487fca0caf034a671d4e60df5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twig/markdown-extra' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => '25ed505b6ffd3b00f922ca682489dfbaf44eb1f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/markdown-extra',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.4.3',
            'version' => '3.4.3.0',
            'reference' => 'c38fd6b0b7f370c198db91ffd02e23b517426b58',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'reference' => '83b609028194aa042ea33b5af2d41a7427de80e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
